import React from "react";
import { Container, Row, Col } from "react-bootstrap";
import ProjectCard from "./ProjectCards";
import Particle from "../Particle";
import sbm from "../../Assets/Projects/sbm.png";
import movie from "../../Assets/Projects/movie.png";

function Projects() {
  return (
    <Container fluid className="project-section">
      <Particle />
      <Container>
        <h1 className="project-heading">
          My Recent <strong className="purple">Works </strong>
        </h1>
        <p style={{ color: "white" }}>
          Here are a few projects I've worked on.
        </p>
        <Row style={{ justifyContent: "center", paddingBottom: "10px" }}>
          <Col md={4} className="project-card">
            <ProjectCard
              imgPath={sbm}
              isBlog={false}
              title="Service Booking Management"
              description="Developed a service booking portal where vendors can register, upload, and manage their services. Utilized the Spring Framework to build five microservices to handle endpoint requests generated by the client-side UI, which was developed using React JS."
              ghLink="https://github.com/chetankandarkar/service-booking-management"
            />
          </Col>

          <Col md={4} className="project-card">
            <ProjectCard
              imgPath={movie}
              isBlog={false}
              title="Movie Booking Portal"
              description="Developed a movie booking application that allows users to register, log in, and search for released movies. Users can book tickets for the movies they wish to watch. Admins can view all booked tickets and update the availability of pending tickets in the system."
              ghLink="https://github.com/chetankandarkar/movie-booking"
            />
          </Col>

          
        </Row>
      </Container>
    </Container>
  );
}

export default Projects;
